/* This file is auto-generated by Rake */

/* Build Host Info:
 * - Host Name: 221903d37a40
 * - Kernel Build: Linux version 5.4.0-135-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
 * - Build Timestamp: 2022-12-31 11:47:45 +0000
 * - Ruby Version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
 * - Rake Version: rake, version 13.0.3
 */

/*
 * Source Control Info:
 * - Submodule:
 *    bdf2c2c2eeaf3a9e33173c85a8d311af0e9c9acc emrun (segger/3.10.1-1-12-gbdf2c2c)
 */

#ifndef __NUCLEI_SEGGER_RTL_RELEASE_H
#define __NUCLEI_SEGGER_RTL_RELEASE_H 1

#define __NUCLEI_SEGGER_RTL_RELEASE_COMMIT "9d011778e5156e9124e6acd7dd00ceacbb963dcb"

#endif /* __NUCLEI_SEGGER_RTL_RELEASE_H */
